version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      minor-development-deps:
        dependency-type: 'development'
        update-types:
          - minor
          - patch
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      - dependency-name: react
        versions:
          - ">= 16"
      - dependency-name: react-dom
        versions:
          - ">= 16"
      - dependency-name: "@testing-library/react"
        versions:
          - ">= 13"
