name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
        react: [16, 17, 18]

    name: build (${{ matrix.node }} w/ React ${{ matrix.react }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # Node 14 ships with npm@6 which doesn't install peerDeps by default.
      - name: Install npm@7
        if: matrix.node == '14'
        run: npm install -g npm@7

      - name: Install deps
        run: npm ci

      - name: Install React ${{ matrix.react }}
        run: npm i react@${{ matrix.react }} react-dom@${{ matrix.react }}

      - name: Run tests
        run: npm test
